# Loader metadata
modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/AlcatrazEscapee/HexLands/issues"

[[mods]]
    modId = "hexlands"
    version = "${file.jarVersion}"
    displayName = "HexLands"
    credits = "By AlcatrazEscapee, based on original work by superfluke et. al."
    authors = "AlcatrazEscapee"
    description = "Remakes the overworld, Settlers of Catan style."

[[dependencies.hexlands]]
    modId = "forge"
    mandatory = true
    versionRange = "[38.0.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.hexlands]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.1,)"
    ordering = "AFTER"
    side = "BOTH"
